

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
r1 <- read.csv("https://raw.githubusercontent.com/p-ai-org/p-laying_soccer/main/Final-Models/data/roundone.csv")

r2 <- read.csv("https://raw.githubusercontent.com/p-ai-org/p-laying_soccer/main/Final-Models/data/roundtwo.csv")
  
r3 <- read.csv("https://raw.githubusercontent.com/p-ai-org/p-laying_soccer/main/Final-Models/data/roundthree.csv")

r4 <- read.csv("https://raw.githubusercontent.com/p-ai-org/p-laying_soccer/main/Final-Models/data/roundfour.csv")

r53 <- read.csv("https://raw.githubusercontent.com/p-ai-org/p-laying_soccer/main/Final-Models/data/roundfive.csv")
```

```{r}
eng_final <- r53 %>%
  filter(team_id == 865)
eng_final <- cbind(match_num=c(1,2,3,4,5),eng_final)
eng_pred <- eng_final[1,]

ger_final <- r53 %>%
  filter(team_id == 857)
ger_final <- cbind(match_num=c(1,2,3,4,5),ger_final)
ger_pred <- ger_final[1,]
```

```{r}
eng_final
ger_final
```
```{r}
plot(eng_final$match_num,eng_final$percentfirsttime)
abline(lm(eng_final$percentfirsttime ~ eng_final$match_num))

y <- eng_final$percentfirsttime
x <- eng_final$match_num
eng_pred[1,8] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
eng_pred[1,8]
```

```{r}
plot(eng_final$match_num,eng_final$duration_perc)
abline(lm(eng_final$duration_perc ~ eng_final$match_num))

y <- eng_final$duration_perc
x <- eng_final$match_num
eng_pred[1,9] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
```

```{r}
plot(eng_final$match_num,eng_final$num_crosses)
abline(lm(eng_final$num_crosses ~ eng_final$match_num))

y <- eng_final$num_crosses
x <- eng_final$match_num
eng_pred[1,10] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
eng_pred[1,10]
```

```{r}
plot(eng_final$match_num,eng_final$Total_shots)
abline(lm(eng_final$Total_shots ~ eng_final$match_num))

y <- eng_final$Total_shots
x <- eng_final$match_num
eng_pred[1,11] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
eng_pred[1,11]
```
```{r}
plot(eng_final$match_num,eng_final$Ratio_of_Shots)
abline(lm(eng_final$Ratio_of_Shots ~ eng_final$match_num))

y <- eng_final$Ratio_of_Shots
x <- eng_final$match_num
eng_pred[1,12] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
eng_pred[1,12]
```
```{r}
plot(eng_final$match_num,eng_final$numshotassist)
abline(lm(eng_final$numshotassist ~ eng_final$match_num))

y <- eng_final$numshotassist
x <- eng_final$match_num
eng_pred[1,13] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
eng_pred[1,13]
```

```{r}
eng_pred[,7:13]
```

```{r}
y <- ger_final$percentfirsttime
x <- ger_final$match_num
ger_pred[1,8] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
ger_pred[1,8]
y <- ger_final$duration_perc
x <- ger_final$match_num
ger_pred[1,9] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
ger_pred[1,9]
y <- ger_final$num_crosses
x <- ger_final$match_num
ger_pred[1,10] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
ger_pred[1,10]
y <- ger_final$Total_shots
x <- ger_final$match_num
ger_pred[1,11] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
ger_pred[1,11]
y <- ger_final$Ratio_of_Shots
x <- ger_final$match_num
ger_pred[1,12] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
ger_pred[1,12]
y <- ger_final$numshotassist
x <- ger_final$match_num
ger_pred[1,13] <- predict(lm(y ~ x), newdata=data.frame(x=c(6)))
ger_pred[1,13]
```

```{r}
new <- rbind(eng_pred[,7:13],ger_pred[,7:13])
new

new[2,1] <- "Loss"
new

new[1,3] <- new[1,3]/(new[1,3]+new[2,3])
new[2,3] <- 1-new[1,3]
new

new[1,4] <- round(new[1,4])
new[2,4] <- round(new[2,4])
new

new[1,5] <- round(new[1,5])
new[2,5] <- round(new[2,5])
new

new[1,6] <- new[1,5]/new[2,5]
new[2,6] <- 1/new[1,6]
new

new[1,7] <- round(new[1,7])
new[2,7] <- round(new[2,7])
new
```

```{r}
actual <- actualfinalmatch
actual <- actual %>% 
  select(-team.name,-outcome)
actual <- cbind(outcome=c("Win","Loss"),actual)
actual
pred_stats <- rbind(actual,new)
pred_stats <- rbind(pred_stats,list("Loss",.3,0.5,20,1,.5,2))
pred_stats
```

```{r}
pred_stats[3:4,]
```

```{r}
eng <- r5_rf_final %>%
  predict(new_data = eng.df) %>%
  cbind(eng.df)

count.eng <- 0
for(i in 1:length(eng.df[,1])){
  if(eng[i,1]=="Win") count.eng <- count.eng+1
}
count.eng
```

```{R}
eng <- new[1,]
l1 <- c(new[1,2]-.15*new[1,2],new[1,2],new[1,2]+.15*new[1,2])
l2 <- c(new[1,3]-.15*new[1,3],new[1,3],new[1,3]+.15*new[1,3])
l3 <- c(round(new[1,4]-.15*new[1,4]),new[1,4],round(new[1,4]+.15*new[1,4]))
l4 <- c(round(new[1,5]-.15*new[1,5]),new[1,5],round(new[1,5]+.15*new[1,5]))
l5 <- c(new[1,6]-.15*new[1,6],new[1,6],new[1,6]+.15*new[1,6])
l6 <- c(round(new[1,7]-.15*new[1,7]),new[1,7],round(new[1,7]+.15*new[1,7]))
```

```{R}
eng <- new[1,]
l1 <- c(new[1,2]-.1*new[1,2],new[1,2],new[1,2]+.1*new[1,2])
l2 <- c(new[1,3]-.1*new[1,3],new[1,3],new[1,3]+.1*new[1,3])
l3 <- c(round(new[1,4]-.1*new[1,4]),new[1,4],round(new[1,4]+.1*new[1,4]))
l4 <- c(round(new[1,5]-.1*new[1,5]),new[1,5],round(new[1,5]+.1*new[1,5]))
l5 <- c(new[1,6]-.1*new[1,6],new[1,6],new[1,6]+.1*new[1,6])
l6 <- c(round(new[1,7]-.1*new[1,7]),new[1,7],round(new[1,7]+.1*new[1,7]))
```

```{r}
eng.df <- expand.grid(l1,l2,l3,l4,l5,l6)
eng.df <- cbind(outcome=rep("Win",length(eng.df[,1])),eng.df)
eng.df <- eng.df %>%
  rename(
    percentfirsttime=Var1,
    duration_perc=Var2,
    num_crosses=Var3,
    Total_shots=Var4,
    Ratio_of_Shots=Var5,
    numshotassist=Var6
  )
```

```{r}
l1 <- c(new[2,2]-.15*new[2,2],new[2,2],new[2,2]+.15*new[2,2])
l2 <- c(new[2,3]-.15*new[2,3],new[2,3],new[2,3]+.15*new[2,3])
l3 <- c(round(new[2,4]-.15*new[2,4]),new[2,4],round(new[2,4]+.15*new[2,4]))
l4 <- c(round(new[2,5]-.15*new[2,5]),new[2,5],round(new[2,5]+.15*new[2,5]))
l5 <- c(new[2,6]-.15*new[2,6],new[2,6],new[2,6]+.15*new[2,6])
l6 <- c(round(new[2,7]-.15*new[2,7]),new[2,7],round(new[2,7]+.15*new[2,7]))
```

```{r}
l1 <- c(new[2,2]-.1*new[2,2],new[2,2],new[2,2]+.15*new[2,2])
l2 <- c(new[2,3]-.1*new[2,3],new[2,3],new[2,3]+.15*new[2,3])
l3 <- c(round(new[2,4]-.15*new[2,4]),new[2,4],round(new[2,4]+.15*new[2,4]))
l4 <- c(round(new[2,5]-.15*new[2,5]),new[2,5],round(new[2,5]+.15*new[2,5]))
l5 <- c(new[2,6]-.15*new[2,6],new[2,6],new[2,6]+.15*new[2,6])
l6 <- c(round(new[2,7]-.15*new[2,7]),new[2,7],round(new[2,7]+.15*new[2,7]))
```

```{r}
ger.df <- expand.grid(l1,l2,l3,l4,l5,l6)
ger.df <- cbind(outcome=rep("Win",length(ger.df[,1])),ger.df)
ger.df <- ger.df %>%
  rename(
    percentfirsttime=Var1,
    duration_perc=Var2,
    num_crosses=Var3,
    Total_shots=Var4,
    Ratio_of_Shots=Var5,
    numshotassist=Var6
  )
```


```{r}
ger <- r5_rf_final %>%
  predict(new_data = ger.df) %>%
  cbind(ger.df)

count.ger <- 0
for(i in 1:length(ger.df[,1])){
  if(ger[i,1]=="Win") count.ger <- count.ger+1
}
count.ger
```






